export { Auth } from './Auth'
export { Contact } from './Contact'
export { Home } from './Home'
export { NotFound } from './NotFound'
export { Payment } from './Payment'
export { Plans } from './Plans'
export { Privacy } from './Privacy'
export { Profile } from './Profile'
export { Pending, Room, Rooms } from './Rooms'
export { Terms } from './Terms'
